mogrify -format jpg data/class-images/00000/*.ppm
mogrify -format jpg data/class-images/00001/*.ppm
mogrify -format jpg data/class-images/00002/*.ppm
mogrify -format jpg data/class-images/00003/*.ppm
mogrify -format jpg data/class-images/00004/*.ppm
mogrify -format jpg data/class-images/00005/*.ppm
mogrify -format jpg data/class-images/00006/*.ppm
mogrify -format jpg data/class-images/00007/*.ppm
mogrify -format jpg data/class-images/00008/*.ppm
mogrify -format jpg data/class-images/00009/*.ppm
mogrify -format jpg data/class-images/00010/*.ppm
mogrify -format jpg data/class-images/00011/*.ppm
mogrify -format jpg data/class-images/00012/*.ppm
mogrify -format jpg data/class-images/00013/*.ppm
mogrify -format jpg data/class-images/00014/*.ppm
mogrify -format jpg data/class-images/00015/*.ppm
mogrify -format jpg data/class-images/00016/*.ppm
mogrify -format jpg data/class-images/00017/*.ppm
mogrify -format jpg data/class-images/00018/*.ppm
mogrify -format jpg data/class-images/00019/*.ppm
mogrify -format jpg data/class-images/00020/*.ppm
mogrify -format jpg data/class-images/00021/*.ppm
mogrify -format jpg data/class-images/00022/*.ppm
mogrify -format jpg data/class-images/00023/*.ppm
mogrify -format jpg data/class-images/00024/*.ppm
mogrify -format jpg data/class-images/00025/*.ppm
mogrify -format jpg data/class-images/00026/*.ppm
mogrify -format jpg data/class-images/00027/*.ppm
mogrify -format jpg data/class-images/00028/*.ppm
mogrify -format jpg data/class-images/00029/*.ppm
mogrify -format jpg data/class-images/00030/*.ppm
mogrify -format jpg data/class-images/00031/*.ppm
mogrify -format jpg data/class-images/00032/*.ppm
mogrify -format jpg data/class-images/00033/*.ppm
mogrify -format jpg data/class-images/00034/*.ppm
mogrify -format jpg data/class-images/00035/*.ppm
mogrify -format jpg data/class-images/00036/*.ppm
mogrify -format jpg data/class-images/00037/*.ppm
mogrify -format jpg data/class-images/00038/*.ppm
mogrify -format jpg data/class-images/00039/*.ppm
mogrify -format jpg data/class-images/00040/*.ppm
mogrify -format jpg data/class-images/00041/*.ppm
mogrify -format jpg data/class-images/00042/*.ppm

rm data/class-images/*/*.ppm